import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import dayjs from "dayjs";

/**
 * Interface for Export Metadata
 */
interface ExportMetadata {
    title: string;
    generatedBy: string;
    dateRange: string;
    filters: { label: string; value: string }[];
    fileName: string;
}

/**
 * Common Utility for Exporting Reports to PDF
 */
export const exportToPDF = (
    metadata: ExportMetadata,
    headers: string[],
    data: any[][]
) => {
    const doc = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4'
    });

    const { title, generatedBy, dateRange, filters, fileName } = metadata;

    // Header Background
    doc.setFillColor(79, 70, 229); // Indigo-600
    doc.rect(0, 0, 297, 40, 'F');

    // Title
    doc.setFontSize(24);
    doc.setTextColor(255);
    doc.text(title.toUpperCase(), 15, 20);

    // Date Range (Sub-header)
    doc.setFontSize(12);
    doc.text(`Period: ${dateRange}`, 15, 30);

    // Metadata Section
    doc.setTextColor(50);
    doc.setFontSize(10);
    let currentY = 50;

    // Left Side: Generated Info
    doc.setFont("helvetica", "bold");
    doc.text("REPORT INFORMATION", 15, currentY);
    doc.setFont("helvetica", "normal");
    currentY += 6;
    doc.text(`Generated By: ${generatedBy}`, 15, currentY);
    currentY += 5;
    doc.text(`Export Date: ${dayjs().format("DD MMM YYYY, hh:mm A")}`, 15, currentY);

    // Right Side: Filter Details
    let filterY = 50;
    const rightAlignX = 180;
    doc.setFont("helvetica", "bold");
    doc.text("FILTER CRITERIA", rightAlignX, filterY);
    doc.setFont("helvetica", "normal");
    filterY += 6;
    filters.forEach(filter => {
        doc.text(`${filter.label}: ${filter.value}`, rightAlignX, filterY);
        filterY += 5;
    });

    // Table
    autoTable(doc, {
        head: [headers],
        body: data,
        startY: 75,
        margin: { left: 15, right: 15 },
        styles: {
            fontSize: 8,
            cellPadding: 4,
            valign: 'middle',
        },
        headStyles: {
            fillColor: [79, 70, 229],
            textColor: 255,
            fontStyle: 'bold',
            halign: 'center'
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252]
        },
        columnStyles: {
            0: { halign: 'center' },
        },
        didDrawPage: (data) => {
            // Footer
            const str = "Page " + data.pageNumber;
            doc.setFontSize(10);
            doc.setTextColor(150);
            doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
            doc.text("Inventory Management System - Confidential", data.settings.margin.left + 80, doc.internal.pageSize.height - 10);
        }
    });

    doc.save(`${fileName}_${dayjs().format("YYYYMMDD_HHmm")}.pdf`);
};

/**
 * Common Utility for Exporting Reports to Excel
 */
export const exportToExcel = async (
    metadata: ExportMetadata,
    headers: string[],
    data: any[][]
) => {
    const { title, generatedBy, dateRange, filters, fileName } = metadata;
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Report");

    // Title Row
    const titleRow = worksheet.addRow([title.toUpperCase()]);
    titleRow.font = { size: 18, bold: true, color: { argb: 'FFFFFF' } };
    titleRow.height = 35;
    worksheet.mergeCells(`A1:${String.fromCharCode(64 + headers.length)}1`);
    titleRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '4F46E5' } };
    titleRow.getCell(1).alignment = { vertical: 'middle', horizontal: 'center' };

    // Sub-header Info
    worksheet.addRow([]); // Gap

    const infoRow1 = worksheet.addRow(["Report Period:", dateRange]);
    infoRow1.getCell(1).font = { bold: true };

    const infoRow2 = worksheet.addRow(["Generated By:", generatedBy]);
    infoRow2.getCell(1).font = { bold: true };

    const infoRow3 = worksheet.addRow(["Export Date:", dayjs().format("DD MMM YYYY, hh:mm A")]);
    infoRow3.getCell(1).font = { bold: true };

    // Filters
    worksheet.addRow([]); // Gap
    const filterSummaryRow = worksheet.addRow(["FILTER CRITERIA"]);
    filterSummaryRow.getCell(1).font = { bold: true, underline: true };

    filters.forEach(f => {
        const row = worksheet.addRow([f.label + ":", f.value]);
        row.getCell(1).font = { italic: true };
    });

    worksheet.addRow([]); // Gap

    // Main Headers
    const headerRow = worksheet.addRow(headers);
    headerRow.height = 25;
    headerRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '4F46E5' } };
        cell.font = { color: { argb: 'FFFFFF' }, bold: true };
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
        cell.border = {
            top: { style: 'thin' },
            left: { style: 'thin' },
            bottom: { style: 'thin' },
            right: { style: 'thin' },
        };
    });

    // Data Rows
    data.forEach((rowData) => {
        const row = worksheet.addRow(rowData);
        row.height = 20;
        row.eachCell((cell) => {
            cell.alignment = { vertical: 'middle', horizontal: 'center' };
            cell.border = {
                top: { style: 'thin' },
                left: { style: 'thin' },
                bottom: { style: 'thin' },
                right: { style: 'thin' },
            };
        });
    });

    // Column Widths
    worksheet.columns.forEach((column, i) => {
        if (i === 0) column.width = 15;
        else if (i === 1) column.width = 25;
        else if (i === 2) column.width = 30;
        else column.width = 18;
    });

    // Write and Save
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    saveAs(blob, `${fileName}_${dayjs().format("YYYYMMDD_HHmm")}.xlsx`);
};
